name: All Tests

on: pull_request

jobs:
  lint:
    name: Lint and typecheck Python code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: citizensadvice/python-uv-setup-action@b146d8feb2c392a8b22a8e06031ee51b8b5b92cb
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3
      - run: just lint

  test:
    name: Run Python tests
    runs-on: ubuntu-latest
    env:
      SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: citizensadvice/python-uv-setup-action@b146d8feb2c392a8b22a8e06031ee51b8b5b92cb
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3
      - run: just all-tests

  docs-update:
    name: Ensure documentation is up to date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: citizensadvice/python-uv-setup-action@b146d8feb2c392a8b22a8e06031ee51b8b5b92cb
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3
      - run: just generate-docs
      - run: git diff --exit-code docs.md || (echo "Documentation is out of date. Please run 'just generate-docs' and commit the changes." && exit 1)

  audit:
    name: Audit Python dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: citizensadvice/python-uv-setup-action@b146d8feb2c392a8b22a8e06031ee51b8b5b92cb
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3
      - run: just audit

  tests-successful:
    name: All Checks Passed
    runs-on: ubuntu-latest
    if: always()
    needs: [lint, test, docs-update]
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe
        with:
          jobs: ${{ toJSON(needs) }}
